#=============================================================================
# init.toml
# Author: Wedsley Fernando Da Silva Milouchine 
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    #set tab identation
    default_indent = 4
    expand_tab = false

    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "dracula" 
	colorscheme_bg ="dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode_symbols = true

    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true

    # Set FileTree to Left
    filetree_direction = "left"
    filemanager = "nerdtree"

# Enable autocomplete layer
[[layers]]
  name = "lsp"

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"

[[layers]]
  name = "incsearch"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 20

[[layers]]
  name = "code#tabline"
  enable = false

[[layers]]
  name = "core#statusline"
  enable = false


#===================================================
# Custom Plugins by Wedsley Fernando
#===================================================

[[custom_plugins]]
  repo = "rafi/awesome-vim-colorschemes"
  merged = false

[[custom_plugins]]
  repo = "wakatime/vim-wakatime"
  merged = false

[[custom_plugins]]
  repo = "ryanoasis/vim-devicons"
  merged = false

[[custom_plugins]]
  repo = "crusoexia/vim-monokai"
  merged = false

[[custom_plugins]]
  repo = "dracula/vim"
  name = "dracula"
  merged = false

[[custom_plugins]]
  repo ="johngrib/vim-game-code-break"
  name ="game_code_break"
  merged = false

[[custom_plugins]]
  repo ="vim-airline/vim-airline-themes"
  name ="theme_airline"
  merged = false

[[custom_plugins]]
  repo = "ctrlpvim/ctrlp.vim"
  name = "ctrlpvim"
  merged = false

[[custom_plugins]]
  repo = "nvim-lua/popup.nvim"
  name = "popup"
  merged = false

[[custom_plugins]]
  repo = "nvim-lua/plenary.nvim"
  name = "plenary"
  merged = false

[[custom_plugins]]
  repo = "nvim-telescope/telescope.nvim"
  name = "telescope"
  merged = false

[[custom_plugins]]
  repo = "nvim-telescope/telescope-fzy-native.nvim"
  name = "telescope-fzy"
  merged = false

[[custom_plugins]]
  repo = "norcalli/nvim-colorizer.lua"
  name = "colorized"
  merged = false

[[custom_plugins]]
  repo = "airblade/vim-gitgutter"
  name = "vim-gitgutter"
  merged = false

[[custom_plugins]]
  repo = "will133/vim-dirdiff"
  name = "vim-dirdiff"
  merged = false

[[custom_plugins]]
  repo = "chrisbra/unicode.vim"
  name = "vim-unicode"
  merged = false

[[custom_plugins]]
  repo = "romgrk/barbar.nvim"
  name = "nvim-barbar"
  merged = false

[[custom_plugins]]
  repo = "kyazdani42/nvim-web-devicons"
  name = "nvim-web-devicons"
  merged = false
